theme = "catppuccin_macchiato"

[editor]
bufferline = "multiple"
true-color = true
line-number = "relative"
insert-final-newline = false
cursorline = true
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]
indent-heuristic = "tree-sitter"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "│"
render = true

[editor.file-picker]
git-ignore = false
