return {
    "echasnovski/mini.nvim",
    version = false,
    config = function()
        require("mini.basics").setup()
        require("mini.ai").setup()
        require("mini.align").setup()
        -- require('mini.animate').setup()
        -- require("mini.bracketed").setup()
        require("mini.bufremove").setup()
        require("mini.comment").setup()
        -- require("mini.completion").setup()
        require("mini.cursorword").setup()
        -- require("mini.diff").setup()
        require("mini.extra").setup()
        require("mini.fuzzy").setup()
        require("mini.indentscope").setup({ draw = { animation = require("mini.indentscope").gen_animation.none() } })
        -- require("mini.jump").setup()
        -- require("mini.jump2d").setup()
        -- require("mini.move").setup()
        -- require("mini.notify").setup()
        -- require("mini.operators").setup()
        require("mini.pairs").setup()
        require("mini.sessions").setup()
        require("mini.splitjoin").setup()
        -- require('mini.starter').setup()
        -- require("mini.surround").setup()
        require("mini.trailspace").setup()
        -- require("mini.visits").setup()
    end,
}
